#ifndef GLSL_PREAMBLE
#define GLSL_PREAMBLE

#define MODEL_MAT_LOCATION 0
#define VIEW_MAT_LOCATION 1
#define PROJ_MAT_LOCATION 2
#define AMBIENT_LOCATION 3
#define DIFFUSE_LOCATION 4
#define SPECULAR_LOCATION 5
#define SHININESS_LOCATION 6
#define SINGLE_COLOR_LOCATION 7
#define FOR_SHADOW_LOCATION 8
#define FOR_UI_LOCATION 9
#define ONLY_TEXTURE_LOCATION 10
#define SHADOW_VIEW_MAT_LOCATION 11
#define SHADOW_PROJ_MAT_LOCATION 12
#define SHADOW_2_VIEW_MAT_LOCATION 13
#define SHADOW_2_PROJ_MAT_LOCATION 14
#define DRAW_SHADOWS_LOCATION 15

#endif
